import '@servicenow/sdk/global'
import { RestApi } from '@servicenow/sdk/core'
import { listTickets } from '../../server/rest/listTickets'
import { getTicket } from '../../server/rest/getTicket'
import { updateTicket } from '../../server/rest/updateTicket'
import { createChildTicket } from '../../server/rest/createChildTicket'
import { uploadTicketAttachmentHandler, uploadTicketAttachmentForAgent } from '../../server/rest/uploadTicketAttachment'
import { getAttachmentDownloadUrlHandler, getAttachmentDownloadUrlForAgent } from '../../server/rest/getAttachmentDownloadUrl'

RestApi({
    $id: Now.ID['tickets-rest-api'],
    name: 'FresherDesk Tickets API',
    serviceId: 'tickets',
    consumes: 'application/json',
    produces: 'application/json',
    enforceAcl: [],
    versions: [
        {
            $id: Now.ID['tickets-api-v1'],
            version: 1,
            isDefault: true,
            shortDescription: 'FresherDesk ticket API v1',
        },
    ],
    routes: [
        {
            $id: Now.ID['tickets-list-route'],
            path: '/tickets',
            method: 'GET',
            script: listTickets,
            authorization: false,
            authentication: false,
            internalRole: false,
            version: 1,
            shortDescription: 'List tickets with optional filters',
        },
        {
            $id: Now.ID['tickets-get-route'],
            path: '/tickets/{id}',
            method: 'GET',
            script: getTicket,
            authorization: false,
            authentication: false,
            internalRole: false,
            version: 1,
            shortDescription: 'Get a single ticket by sys_id or number',
        },
        {
            $id: Now.ID['tickets-update-route'],
            path: '/tickets/{id}',
            method: 'PATCH',
            script: updateTicket,
            authorization: false,
            authentication: false,
            internalRole: false,
            version: 1,
            shortDescription: 'Update ticket status, subject, description, or tags',
        },
        {
            $id: Now.ID['tickets-create-child-route'],
            path: '/tickets/{id}/create_child',
            method: 'POST',
            script: createChildTicket,
            authorization: false,
            authentication: false,
            internalRole: false,
            version: 1,
            shortDescription: 'Create a child ticket under a parent',
        },
        {
            $id: Now.ID['tickets-upload-attachment-route'],
            path: '/tickets/{id}/attachments',
            method: 'POST',
            script: uploadTicketAttachmentHandler,
            authorization: false,
            authentication: false,
            internalRole: false,
            version: 1,
            shortDescription: 'Upload a ticket attachment (API key, base64 JSON)',
        },
        {
            $id: Now.ID['tickets-agent-upload-attachment-route'],
            path: '/agent/tickets/{id}/attachments',
            method: 'POST',
            script: uploadTicketAttachmentForAgent,
            authorization: true,
            authentication: true,
            internalRole: false,
            version: 1,
            shortDescription: 'Upload a ticket attachment from the agent workspace (session auth)',
        },
        {
            $id: Now.ID['tickets-attachment-download-route'],
            path: '/tickets/{id}/attachments/{attachmentId}/download',
            method: 'GET',
            script: getAttachmentDownloadUrlHandler,
            authorization: false,
            authentication: false,
            internalRole: false,
            version: 1,
            shortDescription: 'Refresh a time-limited Azure SAS download URL for an attachment',
        },
        {
            $id: Now.ID['tickets-agent-attachment-download-route'],
            path: '/agent/tickets/{id}/attachments/{attachmentId}/download',
            method: 'GET',
            script: getAttachmentDownloadUrlForAgent,
            authorization: true,
            authentication: true,
            internalRole: false,
            version: 1,
            shortDescription: 'Refresh attachment download URL for the agent workspace (session auth)',
        },
    ],
})
